#!/usr/bin/env bash

THIS_ABSPATH="$(cd "$(dirname "$0")"; pwd)"

if [ "$(cat .nvmrc)" != "$(node --version)" ]; then
  echo "ERROR: use node version $(cat .nvmrc) when releasing!" >&2
  exit 1
fi

"$THIS_ABSPATH/release" nodejs $@
