#!/usr/bin/env bash
set -e

if [ "$(cat .nvmrc)" != "$(node --version)" ]; then
  echo "ERROR: use node version $(cat .nvmrc) when releasing!" >&2
  exit 1
fi

# Update this value to have this repo use a different version of the release.sh script to release itself
RM_USE_VERSION=2.1.0
# Override the version in use if you want to by setting RM_VERSION before invoking this script
RM_VERSION=${RM_VERSION:-$RM_USE_VERSION} # the git ref of the version of the release-management file you want to get

THIS_ABSPATH="$(cd "$(dirname "$0")"; pwd)"

# try with curl or wget, else fallback to docker
if which -s curl; then
  fetch='curl -s '
elif which -s wget; then
  fetch='wget -qO - '
else
  fetch='docker run --rm -i rancher/curl -s '
fi

get() {
  $fetch https://gitlab.com/northscaler-public/release-management/-/raw/$RM_VERSION/$1 >"$THIS_ABSPATH/$1"
}

for it in release.sh tag-nodejs; do
  get $it
  chmod +x $it
done

# Feel free to change this invocation to suit your needs
"$THIS_ABSPATH/release.sh" --pre-rc $@
